package com.rwa.springjerseyrest.Controllers;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;

import com.rwa.springjerseyrest.model.Employee;
import com.rwa.springjerseyrest.service.EmployeeService;

@Controller
@Path("/employee")
public class EmployeeController {
	
	@Autowired
	//@Qualifier("employeeService")
	private EmployeeService employeeService;
	// This means to get the bean called employeeService Which is auto-generated by Spring
	
	
    @GET
    @Produces("application/json")
    public Employee health() {
        return employeeService.getEmployee(1L);
    }
    
   
}